#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! head -1 "$1" | grep -qE "^(feat|fix|hotfix|chore|docs|test|style|refactor|perf|build|ci|revert|release)(\(.+?\))?: .{1,}$"; then
    echo "Missing commit type: feat, fix, chore, docs, test, style, refactor, perf, build, ci, revert, release." >&2
#    exit 1
fi

npx commitlint --edit ${1}
echo "-------------------------------------------"
.git/hooks/commit-msg $1
