#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "------------=[  Lint Branch  ]=------------"
pnpx validate-branch-name
echo "------------=[  Lint Staged  ]=------------"
pnpm lint-staged
echo "------------=[ Type Checking ]=------------"
pnpm check-types
echo "------------=[ Package Audit ]=------------"
pnpm audit
